CREATE TABLE Users (
  Id INT IDENTITY PRIMARY KEY,
  Username NVARCHAR(100) UNIQUE NOT NULL,
  PasswordHash VARBINARY(32) NOT NULL,
  Phone NVARCHAR(20)  NULL,
  Email NVARCHAR(255) NULL,
  CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME()
);
